export interface CityData {
  slug: string;
  name: string;
  county: "Los Angeles" | "Orange County";
  region: string;
  tagline: string;
  about: string;
  heroImg: string;
  landmarks: string[];
  nearby: string[];
}

export const CITIES: CityData[] = [
  // ── LA COUNTY — WESTSIDE & BEACH ──────────────────────────────────────
  {
    slug: "beverly-hills",
    name: "Beverly Hills",
    county: "Los Angeles",
    region: "Westside",
    tagline: "Rodeo Drive · Celebrity Estates · World-Class Luxury",
    about: "Beverly Hills is synonymous with luxury — home to Rodeo Drive, world-class hotels, and the most exclusive estates in California. NexAssist serves Beverly Hills's most discerning residents and visitors with 24/7 personal concierge services across every category of luxury.",
    heroImg: "https://images.unsplash.com/photo-1580655653885-65763b2597d0?w=1600&q=80",
    landmarks: ["Rodeo Drive", "Beverly Hills Hotel", "Spago", "Wilshire Corridor", "Trousdale Estates"],
    nearby: ["bel-air", "west-hollywood", "brentwood", "culver-city", "santa-monica"],
  },
  {
    slug: "bel-air",
    name: "Bel Air",
    county: "Los Angeles",
    region: "Westside",
    tagline: "Gated Estates · Privacy · Old-Money LA",
    about: "Bel Air is one of Los Angeles's most prestigious and private neighborhoods — a gated enclave of multi-million dollar estates, celebrity compounds, and world-class residences. NexAssist provides white-glove concierge services to Bel Air's most exclusive residents.",
    heroImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
    landmarks: ["Hotel Bel-Air", "Bel Air Country Club", "Stone Canyon Reservoir", "Mulholland Drive"],
    nearby: ["beverly-hills", "brentwood", "pacific-palisades", "west-hollywood", "westwood"],
  },
  {
    slug: "brentwood",
    name: "Brentwood",
    county: "Los Angeles",
    region: "Westside",
    tagline: "Upscale Living · San Vicente Corridor · Elite Dining",
    about: "Brentwood is one of LA's most sought-after residential neighborhoods — tree-lined streets, premier dining on San Vicente, and proximity to both the beach and Beverly Hills. A favorite of executives, celebrities, and LA's elite.",
    heroImg: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1600&q=80",
    landmarks: ["Getty Center", "San Vicente Blvd", "Brentwood Country Club", "Barrington Park"],
    nearby: ["pacific-palisades", "bel-air", "santa-monica", "beverly-hills", "culver-city"],
  },
  {
    slug: "pacific-palisades",
    name: "Pacific Palisades",
    county: "Los Angeles",
    region: "Westside",
    tagline: "Clifftop Estates · Canyon Living · Palisades Village",
    about: "Pacific Palisades sits between the Santa Monica Mountains and the Pacific — offering stunning ocean views, estate homes, and a village atmosphere that attracts LA's most successful families and entertainers.",
    heroImg: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1600&q=80",
    landmarks: ["Palisades Village", "Will Rogers State Park", "Gladstones", "Temescal Canyon"],
    nearby: ["malibu", "brentwood", "santa-monica", "bel-air"],
  },
  {
    slug: "santa-monica",
    name: "Santa Monica",
    county: "Los Angeles",
    region: "Westside",
    tagline: "Ocean Boulevard · Third Street Promenade · Beachfront Living",
    about: "Santa Monica is one of LA's most vibrant coastal cities — iconic beachfront, world-class dining on Montana Avenue, and a walkable lifestyle that draws executives, celebrities, and international visitors year-round.",
    heroImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    landmarks: ["Santa Monica Pier", "Third Street Promenade", "Montana Avenue", "Ocean Avenue", "Shutters on the Beach"],
    nearby: ["venice", "malibu", "brentwood", "pacific-palisades", "culver-city"],
  },
  {
    slug: "malibu",
    name: "Malibu",
    county: "Los Angeles",
    region: "Westside",
    tagline: "Beachfront Estates · PCH · Celebrity Coast",
    about: "Malibu is California's most iconic luxury coastal destination — 27 miles of pristine Pacific coastline, celebrity compound estates, world-famous surf breaks, and some of the most expensive real estate in the world.",
    heroImg: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=80",
    landmarks: ["Nobu Malibu", "Soho House Malibu", "Zuma Beach", "Point Dume", "PCH"],
    nearby: ["pacific-palisades", "santa-monica", "calabasas", "agoura-hills"],
  },
  {
    slug: "west-hollywood",
    name: "West Hollywood",
    county: "Los Angeles",
    region: "Westside",
    tagline: "Sunset Strip · Design District · LA's Creative Capital",
    about: "West Hollywood sits at the heart of LA's entertainment and design world — the Sunset Strip, world-class hotels like the Chateau Marmont and Mondrian, and a vibrant luxury lifestyle unlike anywhere else in the city.",
    heroImg: "https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=1600&q=80",
    landmarks: ["Sunset Strip", "Chateau Marmont", "Pacific Design Center", "Melrose Avenue", "Soho House"],
    nearby: ["beverly-hills", "bel-air", "studio-city", "hollywood"],
  },
  {
    slug: "culver-city",
    name: "Culver City",
    county: "Los Angeles",
    region: "Westside",
    tagline: "Arts District · Studios · Silicon Beach",
    about: "Culver City has transformed into one of LA's most exciting urban destinations — home to major studios, a thriving arts district, and a Silicon Beach tech scene that attracts high-net-worth professionals and creatives.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Sony Pictures Studios", "Platform", "Culver City Arts District", "Helms Bakery District"],
    nearby: ["santa-monica", "marina-del-rey", "venice", "beverly-hills"],
  },
  {
    slug: "el-segundo",
    name: "El Segundo",
    county: "Los Angeles",
    region: "South Bay",
    tagline: "Beach Town · LAX Proximity · Aerospace Hub",
    about: "El Segundo is a coastal South Bay city directly adjacent to LAX — ideal for airport transfers, corporate travel, and executives who need seamless luxury service between the airport and the rest of LA.",
    heroImg: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1600&q=80",
    landmarks: ["LAX", "El Segundo Beach", "Main Street El Segundo"],
    nearby: ["manhattan-beach", "hermosa-beach", "inglewood"],
  },
  {
    slug: "marina-del-rey",
    name: "Marina del Rey",
    county: "Los Angeles",
    region: "Westside",
    tagline: "World's Largest Small Craft Harbor · Yacht Life · Waterfront Dining",
    about: "Marina del Rey is home to one of the world's largest small-craft harbors — a waterfront lifestyle destination with luxury yachts, oceanfront restaurants, and seamless access to Venice and Santa Monica.",
    heroImg: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&q=80",
    landmarks: ["Marina del Rey Harbor", "Fisherman's Village", "Villa Marina", "Burton Chace Park"],
    nearby: ["venice", "santa-monica", "culver-city", "playa-del-rey"],
  },
  {
    slug: "venice",
    name: "Venice",
    county: "Los Angeles",
    region: "Westside",
    tagline: "Abbot Kinney · Canals · Beach Culture",
    about: "Venice is LA's most creative and eclectic beachfront neighborhood — Abbot Kinney's boutiques and galleries, the famous Boardwalk, celebrity-filled canals, and a booming luxury residential scene.",
    heroImg: "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=1600&q=80",
    landmarks: ["Abbot Kinney Boulevard", "Venice Canals", "Venice Beach Boardwalk", "Rose Avenue"],
    nearby: ["santa-monica", "marina-del-rey", "culver-city"],
  },
  // ── SOUTH BAY ──────────────────────────────────────────────────────────
  {
    slug: "manhattan-beach",
    name: "Manhattan Beach",
    county: "Los Angeles",
    region: "South Bay",
    tagline: "The Most Expensive Zip Code on the Beach",
    about: "Manhattan Beach is the crown jewel of the South Bay — pristine beaches, walkable downtown, and some of the most coveted real estate in California. Home to executives, athletes, and entertainment industry power players.",
    heroImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    landmarks: ["Manhattan Beach Pier", "The Strand", "Manhattan Beach Village", "Bruce's Beach"],
    nearby: ["hermosa-beach", "redondo-beach", "el-segundo", "torrance"],
  },
  {
    slug: "hermosa-beach",
    name: "Hermosa Beach",
    county: "Los Angeles",
    region: "South Bay",
    tagline: "Beach Town Living · The Strand · South Bay Lifestyle",
    about: "Hermosa Beach is a beloved South Bay coastal city — walk streets, The Strand, and a lively beach scene that attracts affluent professionals seeking the ultimate California beach lifestyle.",
    heroImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    landmarks: ["Hermosa Beach Pier", "The Strand", "Pier Avenue", "Greenbelt"],
    nearby: ["manhattan-beach", "redondo-beach", "el-segundo"],
  },
  {
    slug: "redondo-beach",
    name: "Redondo Beach",
    county: "Los Angeles",
    region: "South Bay",
    tagline: "Marina · Pier · Waterfront Lifestyle",
    about: "Redondo Beach offers a relaxed but affluent coastal lifestyle — a bustling pier, marina, and waterfront restaurants that attract South Bay residents seeking the best of beach living.",
    heroImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    landmarks: ["Redondo Beach Pier", "King Harbor Marina", "International Boardwalk"],
    nearby: ["hermosa-beach", "manhattan-beach", "torrance", "palos-verdes-estates"],
  },
  {
    slug: "torrance",
    name: "Torrance",
    county: "Los Angeles",
    region: "South Bay",
    tagline: "South Bay Hub · Del Amo · Corporate Headquarters",
    about: "Torrance is the largest city in the South Bay — home to major corporate headquarters, Del Amo Fashion Center, and a diverse, affluent community with strong demand for luxury and concierge services.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Del Amo Fashion Center", "Toyota USA HQ", "Torrance Beach", "South Bay Galleria"],
    nearby: ["redondo-beach", "palos-verdes-estates", "carson", "manhattan-beach"],
  },
  {
    slug: "palos-verdes-estates",
    name: "Palos Verdes Estates",
    county: "Los Angeles",
    region: "South Bay",
    tagline: "Clifftop Estates · Ocean Views · Exclusive Peninsula",
    about: "Palos Verdes Estates sits on a dramatic coastal peninsula with sweeping Pacific Ocean views — gated estates, equestrian trails, and a quiet exclusivity that attracts LA's wealthiest families.",
    heroImg: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1600&q=80",
    landmarks: ["Wayfarers Chapel", "Terranea Resort", "Trump National Golf Club", "Abalone Cove"],
    nearby: ["rancho-palos-verdes", "rolling-hills", "torrance", "redondo-beach"],
  },
  {
    slug: "rancho-palos-verdes",
    name: "Rancho Palos Verdes",
    county: "Los Angeles",
    region: "South Bay",
    tagline: "Coastal Bluffs · Terranea · Golf & Ocean Views",
    about: "Rancho Palos Verdes is a scenic clifftop city on the Palos Verdes Peninsula — home to Terranea Resort, Trump National Golf Club, and some of the most breathtaking ocean views in Southern California.",
    heroImg: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1600&q=80",
    landmarks: ["Terranea Resort", "Trump National Golf Club LA", "Point Vicente Lighthouse", "Pelican Cove"],
    nearby: ["palos-verdes-estates", "rolling-hills", "torrance"],
  },
  {
    slug: "rolling-hills",
    name: "Rolling Hills",
    county: "Los Angeles",
    region: "South Bay",
    tagline: "Gated Community · Equestrian · Ultra-Private Estates",
    about: "Rolling Hills is one of the most exclusive gated communities in all of California — equestrian estates, pristine private roads, and a level of privacy that attracts LA's most high-profile residents.",
    heroImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
    landmarks: ["Rolling Hills Country Club", "Palos Verdes Peninsula", "Portuguese Bend"],
    nearby: ["palos-verdes-estates", "rancho-palos-verdes", "torrance"],
  },
  // ── SAN FERNANDO VALLEY ────────────────────────────────────────────────
  {
    slug: "calabasas",
    name: "Calabasas",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "Celebrity Capital · Gated Communities · The Commons",
    about: "Calabasas is one of LA's most famous celebrity zip codes — home to gated communities like The Oaks and The Estates, The Kardashians, and a luxury lifestyle that's known worldwide.",
    heroImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
    landmarks: ["The Oaks at Calabasas", "The Commons at Calabasas", "Calabasas Country Club", "Las Virgenes"],
    nearby: ["hidden-hills", "agoura-hills", "westlake-village", "woodland-hills", "malibu"],
  },
  {
    slug: "hidden-hills",
    name: "Hidden Hills",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "The Most Private Gated City in LA",
    about: "Hidden Hills is a fully gated private city — equestrian-zoned estates, A-list celebrity residents, and an exclusivity that makes it one of the most sought-after addresses in all of Los Angeles.",
    heroImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
    landmarks: ["Hidden Hills Equestrian Center", "Hidden Hills Country Club"],
    nearby: ["calabasas", "agoura-hills", "westlake-village"],
  },
  {
    slug: "westlake-village",
    name: "Westlake Village",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "Lakefront Estates · Four Seasons · Affluent Enclave",
    about: "Westlake Village straddles the LA/Ventura County border — a pristine lakefront community with the Four Seasons Westlake Village, world-class golf courses, and some of the valley's finest estates.",
    heroImg: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1600&q=80",
    landmarks: ["Four Seasons Westlake Village", "Westlake Lake", "North Ranch Country Club", "Promenade at Westlake"],
    nearby: ["calabasas", "hidden-hills", "agoura-hills", "thousand-oaks"],
  },
  {
    slug: "woodland-hills",
    name: "Woodland Hills",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "Warner Center · Luxury Valley Living",
    about: "Woodland Hills is the premier business and residential district of the western San Fernando Valley — home to Warner Center, upscale neighborhoods, and a thriving luxury lifestyle community.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Warner Center", "Village at Westfield Topanga", "Woodland Hills Country Club"],
    nearby: ["calabasas", "encino", "tarzana", "westlake-village"],
  },
  {
    slug: "encino",
    name: "Encino",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "Celebrity Enclave · Ventura Boulevard · Valley Estates",
    about: "Encino is one of the most desirable addresses in the San Fernando Valley — large estate lots, a vibrant Ventura Boulevard dining scene, and a long history as a celebrity and entertainment industry enclave.",
    heroImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
    landmarks: ["Ventura Boulevard", "Los Encinos State Historic Park", "Encino Hills", "Balboa Park"],
    nearby: ["sherman-oaks", "tarzana", "woodland-hills", "studio-city"],
  },
  {
    slug: "sherman-oaks",
    name: "Sherman Oaks",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "Valley Hub · Galleria · Affluent Residential",
    about: "Sherman Oaks is a vibrant, centrally located San Fernando Valley community — upscale shopping at the Galleria, excellent dining along Ventura Boulevard, and convenient access to the entire LA metro.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Sherman Oaks Galleria", "Ventura Boulevard", "Sherman Oaks Castle Park"],
    nearby: ["encino", "studio-city", "van-nuys", "burbank"],
  },
  {
    slug: "studio-city",
    name: "Studio City",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "Hollywood Adjacent · Ventura Blvd · Entertainment Industry",
    about: "Studio City sits at the foot of the Hollywood Hills — a walkable, upscale neighborhood beloved by entertainment industry professionals, with world-class dining on Ventura Boulevard and quick access to both the Valley and Hollywood.",
    heroImg: "https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=1600&q=80",
    landmarks: ["CBS Studio Center", "Ventura Boulevard", "Fryman Canyon", "Universal Studios"],
    nearby: ["burbank", "sherman-oaks", "encino", "west-hollywood"],
  },
  {
    slug: "burbank",
    name: "Burbank",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "Media Capital · Hollywood Studios · Airport Hub",
    about: "Burbank is the media capital of the world — home to Warner Bros., Disney, and NBC studios. With Burbank Airport offering convenient private aviation access, it's a critical hub for entertainment industry executives.",
    heroImg: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1600&q=80",
    landmarks: ["Warner Bros. Studios", "Disney Studios", "Burbank Airport (BUR)", "NBC Studios", "Magnolia Park"],
    nearby: ["glendale", "studio-city", "sherman-oaks", "pasadena"],
  },
  {
    slug: "glendale",
    name: "Glendale",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "Americana at Brand · Crescenta Valley · Growing Luxury Market",
    about: "Glendale is a thriving city just north of LA with upscale shopping at Americana at Brand, excellent dining, and an affluent residential community that increasingly demands premium concierge services.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Americana at Brand", "Glendale Galleria", "Forest Lawn Memorial Park", "Brand Park"],
    nearby: ["burbank", "pasadena", "studio-city"],
  },
  {
    slug: "agoura-hills",
    name: "Agoura Hills",
    county: "Los Angeles",
    region: "San Fernando Valley",
    tagline: "Las Virgenes · Wine Country Gateway · Nature Estates",
    about: "Agoura Hills is a scenic foothill community on the western edge of LA County — nestled between the Santa Monica Mountains and Malibu Creek, with estate living, equestrian properties, and access to some of California's most beautiful natural landscapes.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Malibu Creek State Park", "Agoura Hills Country Club", "Reyes Adobe Park"],
    nearby: ["calabasas", "hidden-hills", "westlake-village", "malibu"],
  },
  // ── EAST / CENTRAL LA ──────────────────────────────────────────────────
  {
    slug: "pasadena",
    name: "Pasadena",
    county: "Los Angeles",
    region: "East LA",
    tagline: "Rose Bowl · Old Town · Architectural Grandeur",
    about: "Pasadena is one of Southern California's most beautiful and storied cities — the Rose Bowl, Old Town's world-class dining and shopping, and magnificent Craftsman and Spanish Colonial estates that attract the region's most successful professionals.",
    heroImg: "https://images.unsplash.com/photo-1580655653885-65763b2597d0?w=1600&q=80",
    landmarks: ["Rose Bowl Stadium", "Old Town Pasadena", "The Huntington Library", "Norton Simon Museum", "Caltech"],
    nearby: ["san-marino", "la-canada-flintridge", "arcadia", "glendale", "monrovia"],
  },
  {
    slug: "san-marino",
    name: "San Marino",
    county: "Los Angeles",
    region: "East LA",
    tagline: "The Huntington · Old Money · Estate Living",
    about: "San Marino is one of California's wealthiest small cities — immaculate tree-lined streets, mansion estates, and the world-famous Huntington Library. Consistently one of the highest-income zip codes in Los Angeles County.",
    heroImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
    landmarks: ["The Huntington Library, Art Museum & Botanical Gardens", "Lacy Park", "San Marino Club"],
    nearby: ["pasadena", "arcadia", "la-canada-flintridge", "alhambra"],
  },
  {
    slug: "la-canada-flintridge",
    name: "La Cañada Flintridge",
    county: "Los Angeles",
    region: "East LA",
    tagline: "Foothill Estates · NASA JPL · Descanso Gardens",
    about: "La Cañada Flintridge is a prestigious foothill community known for excellent schools, stunning estate properties, and proximity to both Pasadena and the San Gabriel Mountains — a favorite of scientists, executives, and established LA families.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Descanso Gardens", "NASA JPL", "Flintridge Preparatory School", "Angeles National Forest"],
    nearby: ["pasadena", "glendale", "san-marino", "arcadia"],
  },
  {
    slug: "arcadia",
    name: "Arcadia",
    county: "Los Angeles",
    region: "East LA",
    tagline: "Santa Anita · Luxury Estates · Westfield",
    about: "Arcadia is a prosperous San Gabriel Valley city known for Santa Anita Park, Westfield Santa Anita, and beautiful estate neighborhoods — a growing luxury market driven by an affluent international community.",
    heroImg: "https://images.unsplash.com/photo-1580655653885-65763b2597d0?w=1600&q=80",
    landmarks: ["Santa Anita Park", "LA Arboretum", "Westfield Santa Anita", "Arcadia Country Club"],
    nearby: ["pasadena", "san-marino", "monrovia", "alhambra"],
  },
  {
    slug: "monrovia",
    name: "Monrovia",
    county: "Los Angeles",
    region: "East LA",
    tagline: "Old Town Charm · Foothill Living · Myrtle Avenue",
    about: "Monrovia is a charming foothill city with a vibrant Old Town, beautiful craftsman homes, and a growing affluent community that enjoys easy access to both Pasadena and the San Gabriel Mountains.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Old Town Monrovia", "Myrtle Avenue", "Monrovia Canyon Park"],
    nearby: ["arcadia", "pasadena", "duarte", "azusa"],
  },
  {
    slug: "alhambra",
    name: "Alhambra",
    county: "Los Angeles",
    region: "East LA",
    tagline: "Gateway to San Gabriel Valley · Dining · Growing Affluence",
    about: "Alhambra sits at the gateway to the San Gabriel Valley — a diverse, growing city with a thriving restaurant scene, affordable luxury living, and close proximity to Downtown LA, Pasadena, and the broader SGV.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Main Street Alhambra", "Almansor Park", "San Gabriel Valley"],
    nearby: ["pasadena", "san-marino", "arcadia", "monterey-park"],
  },
  {
    slug: "downey",
    name: "Downey",
    county: "Los Angeles",
    region: "Southeast LA",
    tagline: "Aerospace Heritage · NASA Armstrong · Growing Prosperity",
    about: "Downey is a proud Southeast LA city with deep aerospace heritage — home to NASA's Armstrong Flight Research Center and a thriving, growing community that increasingly demands premium luxury and concierge services.",
    heroImg: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1600&q=80",
    landmarks: ["NASA Armstrong Flight Research Center", "Downey Avenue", "Columbia Memorial Space Center"],
    nearby: ["cerritos", "whittier", "long-beach"],
  },
  {
    slug: "long-beach",
    name: "Long Beach",
    county: "Los Angeles",
    region: "South LA",
    tagline: "Harbor · Queen Mary · Belmont Shore",
    about: "Long Beach is LA County's second-largest city — a thriving port city with a vibrant waterfront, world-class restaurants in Belmont Shore, and a growing luxury scene anchored by the iconic Queen Mary and its international harbor.",
    heroImg: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&q=80",
    landmarks: ["Queen Mary", "Belmont Shore", "Long Beach Harbor", "Aquarium of the Pacific", "Shoreline Village"],
    nearby: ["cerritos", "seal-beach", "huntington-beach", "torrance"],
  },
  {
    slug: "inglewood",
    name: "Inglewood",
    county: "Los Angeles",
    region: "South LA",
    tagline: "SoFi Stadium · Kia Forum · Entertainment Capital",
    about: "Inglewood has transformed into one of LA's most exciting entertainment destinations — SoFi Stadium hosts the Rams and Chargers, the Kia Forum brings world-class concerts, and the city sits minutes from LAX and the beach cities.",
    heroImg: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1600&q=80",
    landmarks: ["SoFi Stadium", "Kia Forum", "Hollywood Park", "LAX"],
    nearby: ["el-segundo", "manhattan-beach", "culver-city"],
  },
  // ── SOUTH LA COUNTY ────────────────────────────────────────────────────
  {
    slug: "cerritos",
    name: "Cerritos",
    county: "Los Angeles",
    region: "Southeast LA",
    tagline: "Planned Excellence · Cerritos Auto Square · Family Affluence",
    about: "Cerritos is one of LA County's most well-planned and prosperous cities — excellent schools, the famous Cerritos Auto Square, and an affluent family community that values premium services and quality.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Cerritos Auto Square", "Cerritos Center for the Performing Arts", "Cerritos Town Center"],
    nearby: ["downey", "long-beach", "whittier", "la-mirada"],
  },
  {
    slug: "whittier",
    name: "Whittier",
    county: "Los Angeles",
    region: "Southeast LA",
    tagline: "Uptown Village · Nixon Library · Hillside Estates",
    about: "Whittier is a charming Southeast LA city with a vibrant Uptown Village, the Richard Nixon Presidential Library, and scenic hillside neighborhoods that attract professionals seeking a quieter, more residential luxury lifestyle.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Richard Nixon Presidential Library", "Uptown Whittier", "Rose Hills Memorial Park"],
    nearby: ["downey", "cerritos", "diamond-bar"],
  },
  {
    slug: "diamond-bar",
    name: "Diamond Bar",
    county: "Los Angeles",
    region: "Southeast LA",
    tagline: "Foothill Estates · Golf · Eastern Gateway",
    about: "Diamond Bar is a planned foothill community in eastern LA County — gated neighborhoods, country club living, and a quiet affluence that makes it an ideal base for executives commuting to both LA and the Inland Empire.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Diamond Bar Golf Course", "South Pointe", "Summitridge Park"],
    nearby: ["walnut", "whittier", "brea", "fullerton"],
  },
  {
    slug: "walnut",
    name: "Walnut",
    county: "Los Angeles",
    region: "Southeast LA",
    tagline: "Equestrian Estates · Mt. San Antonio College",
    about: "Walnut is a quiet, upscale community in eastern LA County — known for equestrian properties, excellent schools at Mt. San Antonio College, and peaceful estate living at the foot of the San Gabriel Mountains.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Mt. San Antonio College", "Suzanne Park", "Walnut Equestrian Trails"],
    nearby: ["diamond-bar", "rowland-heights", "pomona"],
  },
  // ── ORANGE COUNTY ──────────────────────────────────────────────────────
  {
    slug: "newport-beach",
    name: "Newport Beach",
    county: "Orange County",
    region: "OC Coastal",
    tagline: "Fashion Island · Balboa Island · Premier OC Waterfront",
    about: "Newport Beach is Orange County's luxury capital — Fashion Island shopping, Balboa Island, a world-class marina with hundreds of yachts, and one of the most affluent communities in all of California.",
    heroImg: "https://images.unsplash.com/photo-1559827291-72f8d9c44cf5?w=1600&q=80",
    landmarks: ["Fashion Island", "Balboa Island", "Newport Harbor", "Crystal Cove State Park", "Big Canyon Country Club"],
    nearby: ["laguna-beach", "irvine", "costa-mesa", "corona-del-mar"],
  },
  {
    slug: "laguna-beach",
    name: "Laguna Beach",
    county: "Orange County",
    region: "OC Coastal",
    tagline: "Art Capital · Cove Beaches · Clifftop Estates",
    about: "Laguna Beach is California's most beautiful coastal art town — dramatic clifftop estates, world-famous art galleries, pristine cove beaches, and a lifestyle that attracts the most discerning residents in all of Southern California.",
    heroImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    landmarks: ["Heisler Park", "Laguna Art Museum", "Main Beach", "Montage Laguna Beach", "Las Brisas"],
    nearby: ["newport-beach", "dana-point", "laguna-niguel", "aliso-viejo"],
  },
  {
    slug: "dana-point",
    name: "Dana Point",
    county: "Orange County",
    region: "OC Coastal",
    tagline: "Monarch Beach · Ritz-Carlton · Whale Watching Capital",
    about: "Dana Point is a stunning coastal city anchored by Monarch Beach, the Ritz-Carlton Laguna Niguel, and a world-class marina — one of Orange County's most exclusive and scenic destinations.",
    heroImg: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=1600&q=80",
    landmarks: ["Ritz-Carlton Laguna Niguel", "Monarch Beach Resort", "Dana Point Harbor", "Doheny State Beach"],
    nearby: ["laguna-beach", "san-juan-capistrano", "san-clemente", "laguna-niguel"],
  },
  {
    slug: "san-juan-capistrano",
    name: "San Juan Capistrano",
    county: "Orange County",
    region: "OC Coastal",
    tagline: "Mission · Equestrian · Historic Charm",
    about: "San Juan Capistrano is one of California's most historic and charming cities — the iconic Mission, equestrian estates, and a peaceful affluence that appeals to those seeking a quieter, more refined Southern California lifestyle.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Mission San Juan Capistrano", "Los Rios Historic District", "San Juan Hills Golf Club"],
    nearby: ["dana-point", "san-clemente", "laguna-niguel"],
  },
  {
    slug: "san-clemente",
    name: "San Clemente",
    county: "Orange County",
    region: "OC Coastal",
    tagline: "Spanish Village by the Sea · Surf · Coastal Estates",
    about: "San Clemente is Orange County's southernmost coastal gem — a Spanish colonial-style city with world-class surf, stunning ocean view estates, and a laid-back luxury lifestyle at the gateway to San Diego County.",
    heroImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    landmarks: ["San Clemente Pier", "Trestles Surf Break", "Casa Romantica", "Ole Hanson Beach Club"],
    nearby: ["dana-point", "san-juan-capistrano", "laguna-beach"],
  },
  {
    slug: "irvine",
    name: "Irvine",
    county: "Orange County",
    region: "OC Inland",
    tagline: "Tech Hub · Masterplanned Excellence · UCI",
    about: "Irvine is one of America's most successful planned cities — home to major tech campuses, UCI, John Wayne Airport, and a highly affluent, internationally diverse community that demands the very best in luxury services.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["John Wayne Airport (SNA)", "UCI", "Irvine Spectrum", "Fashion Island proximity", "The District"],
    nearby: ["newport-beach", "costa-mesa", "tustin", "mission-viejo", "laguna-niguel"],
  },
  {
    slug: "mission-viejo",
    name: "Mission Viejo",
    county: "Orange County",
    region: "OC Inland",
    tagline: "Lake Lifestyle · Master-Planned · South OC Hub",
    about: "Mission Viejo is one of Orange County's premier master-planned communities — a pristine lake, excellent residential neighborhoods, and an affluent community seeking premium lifestyle services.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Lake Mission Viejo", "The Shops at Mission Viejo", "Saddleback Church"],
    nearby: ["laguna-niguel", "aliso-viejo", "rancho-santa-margarita", "lake-forest"],
  },
  {
    slug: "laguna-niguel",
    name: "Laguna Niguel",
    county: "Orange County",
    region: "OC Coastal",
    tagline: "Ritz-Carlton · Coastal Ridgeline · South OC Prestige",
    about: "Laguna Niguel is one of South Orange County's most desirable cities — stunning ocean-view homes on coastal ridgelines, the Ritz-Carlton Laguna Niguel, and a refined residential lifestyle minutes from the coast.",
    heroImg: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1600&q=80",
    landmarks: ["Ritz-Carlton Laguna Niguel", "Aliso and Wood Canyons Wilderness", "Crown Valley Community Park"],
    nearby: ["laguna-beach", "dana-point", "aliso-viejo", "mission-viejo"],
  },
  {
    slug: "aliso-viejo",
    name: "Aliso Viejo",
    county: "Orange County",
    region: "OC Inland",
    tagline: "Planned Community · South OC Living",
    about: "Aliso Viejo is a well-planned South Orange County city with an active, affluent community, excellent shopping, and convenient access to both Laguna Beach and Irvine's business corridors.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Town Center", "Aliso and Wood Canyons Wilderness Park", "Pacific Park"],
    nearby: ["laguna-niguel", "laguna-beach", "mission-viejo", "lake-forest"],
  },
  {
    slug: "rancho-santa-margarita",
    name: "Rancho Santa Margarita",
    county: "Orange County",
    region: "OC Inland",
    tagline: "Lakeside Living · Quiet Luxury · South OC",
    about: "Rancho Santa Margarita is a pristine planned community centered around a beautiful lake — peaceful, safe, and popular with successful families who value privacy and quality of life in South Orange County.",
    heroImg: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    landmarks: ["Lago Santa Margarita", "Tijeras Creek Golf Club", "RSM Lake"],
    nearby: ["mission-viejo", "aliso-viejo", "lake-forest"],
  },
  {
    slug: "lake-forest",
    name: "Lake Forest",
    county: "Orange County",
    region: "OC Inland",
    tagline: "Sports Park · Growing Prosperity · Central OC",
    about: "Lake Forest is a thriving central Orange County city — home to one of the nation's best sports parks, growing luxury developments, and a large affluent community benefitting from OC's economic strength.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Heritage Hill Historical Park", "Lake Forest Sports Park", "Foothill Ranch Towne Centre"],
    nearby: ["mission-viejo", "rancho-santa-margarita", "irvine"],
  },
  {
    slug: "huntington-beach",
    name: "Huntington Beach",
    county: "Orange County",
    region: "OC Coastal",
    tagline: "Surf City USA · Downtown HB · Coastal Lifestyle",
    about: "Huntington Beach — Surf City USA — is Orange County's most iconic beach city. A lively downtown, world-famous surf, luxury oceanfront properties, and the perfect staging ground for upscale beach experiences.",
    heroImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    landmarks: ["Huntington Beach Pier", "Pacific City", "Downtown HB", "Bolsa Chica Ecological Reserve"],
    nearby: ["seal-beach", "newport-beach", "costa-mesa", "long-beach"],
  },
  {
    slug: "seal-beach",
    name: "Seal Beach",
    county: "Orange County",
    region: "OC Coastal",
    tagline: "Old Town Charm · Quiet Coastal · OC Gateway",
    about: "Seal Beach is a charming, quiet coastal city at the OC/LA border — an intimate Old Town, a beautiful pier, and an affluent residential community that values privacy and a low-key luxury lifestyle.",
    heroImg: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    landmarks: ["Seal Beach Pier", "Old Town Seal Beach", "Surfside Colony"],
    nearby: ["huntington-beach", "long-beach", "newport-beach"],
  },
  {
    slug: "costa-mesa",
    name: "Costa Mesa",
    county: "Orange County",
    region: "OC Inland",
    tagline: "South Coast Plaza · Arts · OC's Cultural Capital",
    about: "Costa Mesa is Orange County's cultural capital — home to South Coast Plaza (one of the world's top-grossing malls), the Segerstrom Center for the Arts, and a vibrant dining and nightlife scene.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["South Coast Plaza", "Segerstrom Center for the Arts", "Triangle Square", "CAMP"],
    nearby: ["newport-beach", "irvine", "huntington-beach", "santa-ana"],
  },
  {
    slug: "fullerton",
    name: "Fullerton",
    county: "Orange County",
    region: "OC North",
    tagline: "Downtown Arts · Heritage Square · CSUF",
    about: "Fullerton is a vibrant North Orange County city with a lively Downtown arts and dining scene, Cal State Fullerton, and an increasingly affluent residential community with strong demand for premium services.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Downtown Fullerton", "Heritage Square", "Cal State Fullerton", "Hillcrest Park"],
    nearby: ["brea", "anaheim", "yorba-linda", "diamond-bar"],
  },
  {
    slug: "brea",
    name: "Brea",
    county: "Orange County",
    region: "OC North",
    tagline: "Brea Mall · Arts Colony · North OC Affluence",
    about: "Brea is a prosperous North Orange County city renowned for its public art program, Brea Mall, and a strong residential community of executives and professionals seeking quality luxury services.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Brea Mall", "Downtown Brea", "Brea Community Center"],
    nearby: ["fullerton", "yorba-linda", "diamond-bar", "anaheim"],
  },
  {
    slug: "anaheim",
    name: "Anaheim",
    county: "Orange County",
    region: "OC North",
    tagline: "Disneyland · Angel Stadium · Convention Capital",
    about: "Anaheim is one of America's top tourist and convention destinations — home to Disneyland, Angel Stadium, Honda Center, and the Anaheim Convention Center. NexAssist serves both visiting VIPs and local residents with premium concierge services.",
    heroImg: "https://images.unsplash.com/photo-1580655653885-65763b2597d0?w=1600&q=80",
    landmarks: ["Disneyland Resort", "Angel Stadium", "Honda Center", "Anaheim Convention Center", "Packing District"],
    nearby: ["fullerton", "brea", "orange", "garden-grove", "irvine"],
  },
  {
    slug: "yorba-linda",
    name: "Yorba Linda",
    county: "Orange County",
    region: "OC North",
    tagline: "Land of Gracious Living · Nixon Library · Hillside Estates",
    about: "Yorba Linda bills itself as the 'Land of Gracious Living' — and for good reason. Upscale hillside estates, horse trails, the Nixon Presidential Library, and one of the highest median incomes in Orange County.",
    heroImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
    landmarks: ["Richard Nixon Presidential Library & Museum", "Yorba Linda Town Center", "Black Gold Golf Club"],
    nearby: ["brea", "anaheim", "fullerton", "diamond-bar"],
  },
  {
    slug: "tustin",
    name: "Tustin",
    county: "Orange County",
    region: "OC Inland",
    tagline: "Tustin Legacy · Old Town · Central OC",
    about: "Tustin is a centrally located Orange County city undergoing significant luxury development at Tustin Legacy — a massive mixed-use project transforming the city into a major destination for upscale living and commerce.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Tustin Legacy", "Old Town Tustin", "The Marketplace"],
    nearby: ["irvine", "santa-ana", "orange", "costa-mesa"],
  },
  {
    slug: "orange",
    name: "Orange",
    county: "Orange County",
    region: "OC Inland",
    tagline: "Old Towne · Chapman University · Central OC",
    about: "The City of Orange features one of Southern California's most charming historic downtowns — Old Towne Orange's antique shops and restaurants, Chapman University, and a thriving central Orange County location.",
    heroImg: "https://images.unsplash.com/photo-1580655653885-65763b2597d0?w=1600&q=80",
    landmarks: ["Old Towne Orange", "Chapman University", "The Block at Orange", "Angel Stadium proximity"],
    nearby: ["anaheim", "santa-ana", "tustin", "villa-park"],
  },
  {
    slug: "garden-grove",
    name: "Garden Grove",
    county: "Orange County",
    region: "OC Inland",
    tagline: "Little Saigon · Crystal Cathedral · Cultural Diversity",
    about: "Garden Grove is a vibrant, culturally rich city in central Orange County — home to the famous Little Saigon district, world-class dining, and a diverse community with strong demand for premium lifestyle services.",
    heroImg: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1600&q=80",
    landmarks: ["Little Saigon", "Crystal Cathedral (Christ Cathedral)", "Garden Grove Main Street"],
    nearby: ["anaheim", "orange", "westminster", "santa-ana"],
  },
  {
    slug: "buena-park",
    name: "Buena Park",
    county: "Orange County",
    region: "OC North",
    tagline: "Knott's Berry Farm · Entertainment Corridor · North OC",
    about: "Buena Park is North OC's entertainment hub — Knott's Berry Farm, Medieval Times, and a busy visitor economy that drives strong demand for VIP transportation, concierge, and luxury experiences.",
    heroImg: "https://images.unsplash.com/photo-1580655653885-65763b2597d0?w=1600&q=80",
    landmarks: ["Knott's Berry Farm", "Medieval Times", "Buena Park Downtown", "Metrolink Station"],
    nearby: ["fullerton", "anaheim", "cerritos", "garden-grove"],
  },
];

export const CITY_MAP = Object.fromEntries(CITIES.map((c) => [c.slug, c]));
